services:
  db:
    image: postgres:15-alpine
    container_name: moex_db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=moexDatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d moexDatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./backend
    container_name: moex_app
    ports:
      - "8081:8081"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/moexDatabase
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CORS_ORIGIN=http://localhost,http://81.200.158.78
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM=${SMTP_FROM}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: moex_frontend
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres_data:
